---
name: Bug Report
about: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["adhameldeeb"]
---

## Bug Description

<!-- A clear and concise description of what the bug is -->

## To Reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

## Expected Behavior

<!-- A clear and concise description of what you expected to happen -->

## Actual Behavior

<!-- What actually happened -->

## Screenshots

<!-- If applicable, add screenshots to help explain your problem -->

## Environment

**Affected Workspace:**

- [ ] `apps/admin`
- [ ] `apps/user`
- [ ] `apps/docs`
- [ ] `packages/ui`
- [ ] `packages/auth`
- [ ] `packages/ai`
- [ ] `services/api`
- [ ] `services/worker`
- [ ] `services/webhooks`
- [ ] Other: ___________

**Browser (if applicable):**

- Browser: [e.g. Chrome, Safari, Edge]
- Version: [e.g. 119]
- OS: [e.g. Windows 11, macOS 14, Ubuntu 22.04]

**Environment:**

- [ ] Local development
- [ ] Azure staging
- [ ] Azure production

**Additional Context:**

- Node version: [e.g. 20.10.0]
- pnpm version: [e.g. 9.12.3]
- Package version (if specific package): [e.g. @aiconnects/ui@1.0.0]

## Error Messages/Logs

<!-- Paste any error messages or relevant logs here -->

```
Paste error messages here
```

## Possible Solution

<!-- Optional: Suggest a fix or reason for the bug -->

## Additional Context

<!-- Add any other context about the problem here -->

## Impact

**Severity:**

- [ ] 🔴 Critical - System is unusable
- [ ] 🟠 High - Major feature broken
- [ ] 🟡 Medium - Feature partially broken
- [ ] 🟢 Low - Minor issue

**Affected Users:**

- [ ] All users
- [ ] Specific user group: ___________
- [ ] Only in specific scenario

## Related Issues

<!-- Link to related issues or PRs -->

- Related to #
- Blocks #
- Blocked by #
