---
name: Security Vulnerability
about: Report a security vulnerability (PRIVATE ONLY - DO NOT USE FOR PUBLIC REPORTS)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: ["adhameldeeb"]
---

<!-- 
âš ï¸ IMPORTANT: DO NOT REPORT SECURITY VULNERABILITIES IN PUBLIC ISSUES âš ï¸

This template is for internal use only. If you're an external researcher:
1. Use GitHub Security Advisory: https://github.com/howaiconnects/aiconnects/security/advisories/new
2. Or email: security@howaiconnects.com

Only proceed if you're authorized to file internal security issues.
-->

## Vulnerability Type

- [ ] SQL Injection
- [ ] Cross-Site Scripting (XSS)
- [ ] Cross-Site Request Forgery (CSRF)
- [ ] Remote Code Execution (RCE)
- [ ] Authentication Bypass
- [ ] Authorization/Privilege Escalation
- [ ] Sensitive Data Exposure
- [ ] Insecure Deserialization
- [ ] Security Misconfiguration
- [ ] Dependency Vulnerability
- [ ] Other: ___________

## Severity (CVSS 3.1)

- [ ] ðŸ”´ Critical (9.0-10.0)
- [ ] ðŸŸ  High (7.0-8.9)
- [ ] ðŸŸ¡ Medium (4.0-6.9)
- [ ] ðŸŸ¢ Low (0.1-3.9)

**CVSS Score:** _____ (if calculated)

## Affected Components

**Workspace:**
- [ ] `apps/admin`
- [ ] `apps/user`
- [ ] `services/api`
- [ ] `services/worker`
- [ ] `services/webhooks`
- [ ] `packages/auth`
- [ ] `packages/ai`
- [ ] Infrastructure
- [ ] Other: ___________

**Affected Versions:**
- Version(s): ___________
- Commit/Tag: ___________

## Vulnerability Description

<!-- Detailed description of the vulnerability -->

## Impact

<!-- What is the potential impact if exploited? -->

**Confidentiality:**
- [ ] None
- [ ] Low
- [ ] High

**Integrity:**
- [ ] None
- [ ] Low
- [ ] High

**Availability:**
- [ ] None
- [ ] Low
- [ ] High

**Scope:**
- [ ] Unchanged
- [ ] Changed

## Steps to Reproduce

<!-- Detailed steps to reproduce the vulnerability -->

1. Step 1
2. Step 2
3. Step 3

## Proof of Concept

<!-- Provide PoC code, screenshots, or curl commands -->

```bash
# PoC commands or code
```

## Technical Details

<!-- Any technical details about the vulnerability -->

**Attack Vector:**
- [ ] Network
- [ ] Adjacent Network
- [ ] Local
- [ ] Physical

**Attack Complexity:**
- [ ] Low
- [ ] High

**Privileges Required:**
- [ ] None
- [ ] Low
- [ ] High

**User Interaction:**
- [ ] None
- [ ] Required

## Mitigation Recommendations

<!-- Your recommendations for fixing this vulnerability -->

1. Short-term mitigation:
2. Long-term fix:
3. Prevention measures:

## References

<!-- Links to CWE, CVE, or relevant security documentation -->

- CWE: ___________
- CVE: ___________ (if applicable)
- References:

## Discovery Information

**Discovered By:** ___________
**Discovery Date:** ___________
**Reported Date:** ___________

## Internal Notes

<!-- For internal team use only -->

**Action Items:**
- [ ] Triage completed
- [ ] Severity confirmed
- [ ] Patch developed
- [ ] Patch tested
- [ ] Security advisory drafted
- [ ] Disclosure coordinated
- [ ] Fix deployed
